49 expression formatter
BalticAmadeus/AblFormatter pull request #140
Opened 2024-08-30 10:51 UTC by gustason

Do not merge!
Currently, 37 tests do not pass because of the bug in #116.

2025-01-20 09:08 UTC, PauliusKu requested changes

2025-01-20 09:08 UTC, PauliusKu commented on src/v2/formatterFramework/FormatterHelper.ts
> +            //     break;
Remove if not needed

2025-01-20 09:08 UTC, PauliusKu commented on src/model/SyntaxNodeType.ts
> +    EqualsSign = "=",
You forgot the fun ones: `eq`, `ne`, `lt` and etc. We need to support those too.

2025-01-20 13:40 UTC, PeterJudgeZA commented on src/model/SyntaxNodeType.ts
> +    EqualsSign = "=",
There are also compound operators `+=` , `-=`, `/=`, `*=`  and the safe navigation operator `?:`

2025-01-20 14:13 UTC, gustason commented on src/model/SyntaxNodeType.ts
> +    EqualsSign = "=",
The compound operators get parsed as part of ```assignment_operator```. Meanwhile, the parsing of the safe navigation operator is not yet implemented by tree-sitter.

2025-01-21 11:57 UTC, PauliusKu commented on src/model/SyntaxNodeType.ts
> +    EqualsSign = "=",
Yeah, that's right, we don't need those here. But regarding `?:` @gustason could you create a ticket for it, so we won't forget. I think on tree-sitter side it should be easy to implement.

2025-01-21 12:06 UTC, PauliusKu approved these changes

2025-01-21 12:06 UTC, merged